title: Szilvi489
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 Displaying my photographs and coding skills at the same place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Szilvi489
icon : /assets/images/base/logo/1pic.png
navSquareColour : '#0a0a0a'
navFontColour : '#ff0000'
nav_fonts:
  - https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap
  - https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap
  - https://fonts.googleapis.com/css2?family=Aldrich&display=swap
  - https://fonts.googleapis.com/css2?family=Bungee&display=swap
  - https://fonts.googleapis.com/css2?family=Plaster&display=swap
  - https://fonts.googleapis.com/css2?family=Protest+Guerrilla&display=swap
  - https://fonts.googleapis.com/css2?family=Stalinist+One&display=swap
  - https://fonts.googleapis.com/css2?family=Tulpen+One&display=swap

# Build settings
theme: null
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css

collections:
    projects:
      output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      enable_crosshair: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
